import { EntryCollection } from 'contentful'
import Head from 'next/head'
import { ICafeFields } from '../src/@types/contentful'
import { getAllCafes } from '../src/lib/getAllCafes'

type Props = {
  cafes: EntryCollection<ICafeFields>
}
export const getStaticProps = async () => {
  const cafes = await getAllCafes()

  return { props: { cafes: JSON.parse(JSON.stringify(cafes)) } }
}
export default function Home({ cafes }: Props) {
  const { items } = cafes
  return (
    <>
      <Head>
        <title>Tokyo Cafe Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {items.map((item) => (
            <div key={item.sys.id}>
              {item.fields.name}: visited at {item.fields.visited}
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
